// Auto-extracted from App.tsx: presentational view over useApp() state.
import { ConfigForm } from "../components/shared";
import { useApp } from "../state/context";

export function SkillsView() {
  const { skillTab, setSkillTab, editingSkillId, isAdmin, skillSearch, setSkillSearch, filteredSkills, skillAgents, toggleSkill, editSkill, deleteSkill, metadata, createSkill, skillDraft, setSkillDraft, resetSkillEditor, skillGeneratorPrompt, setSkillGeneratorPrompt, generateSkillDraft, generatedSkill, useGeneratedSkill, runReadUrl, internetUrl, setInternetUrl, skillResult, toggleAgentSkill } = useApp();
  return (
<section className="skills-workspace">
          <div className="subtabs">
          <button className={skillTab === "library" ? "active" : ""} onClick={() => setSkillTab("library")}>Biblioteca</button>
          <button className={skillTab === "editor" ? "active" : ""} onClick={() => setSkillTab("editor")}>{editingSkillId ? "Editar" : "Crear"}</button>
          <button className={skillTab === "generator" ? "active" : ""} onClick={() => setSkillTab("generator")}>Generador IA</button>
          </div>

          {skillTab === "library" && <section className="panel skills-panel"><div className="section-toolbar"><div><h2>Biblioteca Agent Skills</h2><p className="muted">Cada skill representa una carpeta <code>agents/skills/nombre/</code> con un <code>SKILL.md</code> estándar. Invocación manual: <code>/nombre_skill describe la tarea</code>.</p></div><input value={skillSearch} onChange={(event) => setSkillSearch(event.target.value)} placeholder="Buscar skill..." /></div>{filteredSkills.length === 0 ? <p className="muted">No hay skills que coincidan.</p> : <div className="skill-grid">{filteredSkills.map((skill) => { const assignedAgents = skillAgents(skill.id); return <article className="skill-card" key={skill.id}><div className="skill-card-head"><div><strong>{skill.name}</strong><span>{skill.enabled ? "Activa" : "Desactivada"} · agents/skills/{skill.name}/SKILL.md</span></div>{isAdmin && <label className="switch-row"><input type="checkbox" checked={skill.enabled} onChange={(event) => toggleSkill(skill, event.target.checked)} /> Enabled</label>}</div><p>{skill.description || "Sin descripción."}</p><div className="chip-row"><span className="chip">/{skill.name}</span><span className="chip">triggers: {skill.triggers.join(", ")}</span>{skill.argument_hint && <span className="chip">args: {skill.argument_hint}</span>}{assignedAgents.length ? assignedAgents.map((agent) => <span className="chip" key={agent.id}>{agent.name}</span>) : <span className="chip muted-chip">Sin agentes</span>}</div><details className="card-details"><summary>SKILL.md</summary><pre className="skill-md-preview">{skill.skill_md}</pre></details>{isAdmin && <div className="skill-actions"><button className="text-button" onClick={() => editSkill(skill)}>Editar SKILL.md</button><button className="text-button danger" onClick={() => deleteSkill(skill)}>Borrar</button></div>}<details className="agent-toggle-list card-details"><summary>Asignación ({assignedAgents.length})</summary>{metadata.agents.map((agent) => { const checked = metadata.agentSkills.some((assignment) => assignment.agent_id === agent.id && assignment.skill_id === skill.id); return <label key={agent.id}><input type="checkbox" checked={checked} disabled={!isAdmin} onChange={(event) => toggleAgentSkill(agent.id, skill.id, event.target.checked)} />{agent.name}</label>; })}</details></article>; })}</div>}</section>}

          {skillTab === "editor" && <section className="panel skills-panel"><div className="section-toolbar"><div><h2>{editingSkillId ? "Editar SKILL.md" : "Crear Agent Skill"}</h2><p className="muted">Edita frontmatter YAML y cuerpo Markdown. ObsyGPT guarda la versión estructurada y genera la preview canónica.</p></div>{editingSkillId && <button className="text-button" onClick={resetSkillEditor}>Nueva skill</button>}</div>{!isAdmin ? <p className="muted">Admin role required.</p> : <ConfigForm onSubmit={createSkill} submitLabel={editingSkillId ? "Guardar SKILL.md" : "Crear skill"}><input value={skillDraft.name} onChange={(event) => setSkillDraft({ ...skillDraft, name: event.target.value })} placeholder="name: invoice-risk" required /><input value={skillDraft.description} onChange={(event) => setSkillDraft({ ...skillDraft, description: event.target.value })} placeholder="description: qué hace y cuándo se activa" /><input value={skillDraft.argument_hint} onChange={(event) => setSkillDraft({ ...skillDraft, argument_hint: event.target.value })} placeholder="argument-hint: texto, URL, CSV..." /><label><input type="checkbox" checked={skillDraft.triggers.includes("user")} onChange={(event) => setSkillDraft({ ...skillDraft, triggers: event.target.checked ? Array.from(new Set([...skillDraft.triggers, "user"])) : skillDraft.triggers.filter((trigger) => trigger !== "user") as Array<"user" | "model"> })} /> trigger user</label><label><input type="checkbox" checked={skillDraft.triggers.includes("model")} onChange={(event) => setSkillDraft({ ...skillDraft, triggers: event.target.checked ? Array.from(new Set([...skillDraft.triggers, "model"])) : skillDraft.triggers.filter((trigger) => trigger !== "model") as Array<"user" | "model"> })} /> trigger model</label><textarea value={skillDraft.body} onChange={(event) => setSkillDraft({ ...skillDraft, body: event.target.value })} placeholder="# Instrucciones principales" /><textarea value={skillDraft.resources} onChange={(event) => setSkillDraft({ ...skillDraft, resources: event.target.value })} placeholder="Recursos opcionales: scripts/, templates/, examples/" /><label><input type="checkbox" checked={skillDraft.enabled} onChange={(event) => setSkillDraft({ ...skillDraft, enabled: event.target.checked })} /> Enabled</label></ConfigForm>}</section>}

          {skillTab === "generator" && <section className="panel skills-panel"><h2>Creador de Agent Skill</h2><p className="muted">Describe la capacidad. ObsyGPT genera frontmatter y cuerpo Markdown para un <code>SKILL.md</code> revisable antes de guardar.</p>{!isAdmin ? <p className="muted">Admin role required.</p> : <ConfigForm onSubmit={generateSkillDraft} submitLabel="Generar SKILL.md"><textarea value={skillGeneratorPrompt} onChange={(event) => setSkillGeneratorPrompt(event.target.value)} placeholder="Ejemplo: una skill para leer facturas, detectar riesgos y devolver una tabla de incidencias" required /></ConfigForm>}{generatedSkill && <div className="generated-skill"><h3>agents/skills/{generatedSkill.name}/SKILL.md</h3><p>{generatedSkill.description}</p><pre>{`---\nname: ${generatedSkill.name}\ndescription: ${generatedSkill.description}\nargument-hint: ${generatedSkill.argument_hint}\ntriggers: [${generatedSkill.triggers.map((trigger) => `"${trigger}"`).join(", ")}]\n---\n\n${generatedSkill.body}\n\n## Recursos opcionales\n${generatedSkill.resources}`}</pre><div className="chip-row">{generatedSkill.checklist.map((item) => <span className="chip" key={item}>{item}</span>)}</div>{isAdmin && <button onClick={useGeneratedSkill}>Usar este borrador</button>}</div>}<ConfigForm onSubmit={runReadUrl} submitLabel="Probar Read URL"><input value={internetUrl} onChange={(event) => setInternetUrl(event.target.value)} placeholder="https://example.com" required /></ConfigForm>{skillResult && <pre className="skill-result">{skillResult}</pre>}</section>}
        </section>
  );
}
