// Typed application state shared by the extracted views.
// App.tsx remains the single owner of state and handlers; views consume it
// through useApp() so JSX lives in view files without moving logic.
import { createContext, useContext } from "react";
import type { Dispatch, FormEvent, KeyboardEvent as ReactKeyboardEvent, ReactElement, RefObject, SetStateAction } from "react";
import type {
  AdminSection, Agent, AgentEvent, AgentFallback, AgentRun, AgentTool, AppView, Attachment, CatalogConnector,
  ChatFolder, Conversation, DiagnosticsResponse, GuardrailSettings, HabitSuggestion, HealthResponse, McpServer,
  MemoryItem, Message, MetricsResponse, Model, ModelCheckResponse, PendingApproval, Preferences, Project,
  ProjectDetail, ProjectFilesResponse, ProjectTab, Provider, ProviderDefinition, SettingsSection, SettingsTab,
  Skill, SkillDraftResponse, SkillTab, Source, Task, TaskApproval, TaskEvent, TasksSettings, ToolCall,
  ToolDefinition, User, WorkflowStep
} from "../types";
import type { emptyMetadata } from "../types";

export type AppMetadata = typeof emptyMetadata;

export interface AppState {
  // --- state values ---
  session: User | null;
  authMode: "login" | "register";
  username: string;
  email: string;
  password: string;
  confirmPassword: string;
  conversations: Conversation[];
  folders: ChatFolder[];
  expandedFolders: number[];
  editingMessageIndex: number | null;
  editingMessageDraft: string;
  copiedMessageIndex: number | null;
  activeConversationId: number | null;
  messages: Message[];
  draft: string;
  metadata: AppMetadata;
  runs: AgentRun[];
  events: AgentEvent[];
  sources: Source[];
  toolCalls: ToolCall[];
  attachments: Attachment[];
  selectedAttachmentIds: number[];
  error: string;
  isStreaming: boolean;
  liveActivity: { label: string; detail?: string; iteration?: number; chars?: number; startedAt: number; lastAt: number } | null;
  providerDraft: { name: string; provider_type: string; base_url: string; api_key_env: string; enabled: boolean };
  modelDraft: { provider_id: string; model_name: string; display_name: string; context_window: string; supports_vision: boolean; supports_audio: boolean; supports_tools: boolean; supports_json: boolean; enabled: boolean };
  agentDraft: { name: string; description: string; system_prompt: string; provider_id: string; model_id: string; internet_enabled: boolean; multimodal_enabled: boolean; agentic_mode: boolean };
  agentEditId: number | null;
  agentEditDraft: { name: string; description: string; system_prompt: string; provider_id: string; model_id: string; temperature: string; internet_enabled: boolean; multimodal_enabled: boolean };
  skillDraft: { name: string; description: string; argument_hint: string; triggers: Array<"user" | "model">; body: string; resources: string; enabled: boolean };
  editingSkillId: number | null;
  skillTab: SkillTab;
  skillSearch: string;
  skillGeneratorPrompt: string;
  generatedSkill: SkillDraftResponse | null;
  mcpDraft: { name: string; description: string; connection_type: string; command: string; url: string; enabled: boolean };
  workflowDraft: { name: string; workflow_type: string; agent_ids: number[] };
  selectedWorkflowId: string;
  selectedAgentId: string;
  internetUrl: string;
  skillResult: string;
  mcpValidation: string;
  catalogConnectors: CatalogConnector[];
  pluginCatalog: import("../types").PluginCatalogEntry[];
  pluginMarketplaces: import("../types").PluginMarketplace[];
  marketplaceDraft: string;
  pluginBusy: string | null;
  pluginMessage: string;
  connectorTokenDrafts: Record<string, string>;
  connectorBusy: string | null;
  connectorMessage: string;
  mcpInspection: { serverId: number; tools: Array<{ name: string; description?: string }> } | null;
  inspectingMcp: number | null;
  mcpRunDraft: { server_id: string; method: string; params: string };
  mcpRunResult: string;
  health: HealthResponse | null;
  modelCheckResult: ModelCheckResponse | null;
  diagnostics: DiagnosticsResponse | null;
  metrics: MetricsResponse | null;
  metricsDays: number;
  auditLogs: import("../types").AuditLog[];
  auditLogLimit: number;
  auditFilters: { action: string; target_type: string };
  agentTools: AgentTool[];
  toolDefinitions: ToolDefinition[];
  agentFallbacks: AgentFallback[];
  pendingApprovals: PendingApproval[];
  resumingApprovalId: number | null;
  detectedModels: Record<number, import("../types").DetectedModel[]>;
  detectingProvider: number | null;
  fallbackDraft: Record<number, { provider_id: string; model_id: string }>;
  chatMode: "act" | "plan" | "think";
  paletteIndex: number;
  activeView: AppView;
  settingsSection: SettingsSection;
  settingsTab: SettingsTab;
  settingsSearch: string;
  tasks: Task[];
  taskDraft: { goal: string; mode: string; scheduled_at: string; recurrence: string };
  expandedTaskId: number | null;
  taskEvents: Record<number, TaskEvent[]>;
  taskApprovals: Record<number, TaskApproval[]>;
  memories: MemoryItem[];
  habitSuggestions: HabitSuggestion[];
  memoryDraft: { content: string; kind: string };
  workspaceInfo: import("../types").WorkspaceInfo | null;
  workspaceDraft: string;
  preferences: Preferences | null;
  guardrailDraft: GuardrailSettings;
  tasksSettings: TasksSettings;
  historySearch: string;
  projects: Project[];
  projectDetail: ProjectDetail | null;
  projectDraft: { name: string; description: string; instructions: string; folder_path: string };
  projectInstructionsDraft: string;
  projectTab: ProjectTab;
  projectFiles: ProjectFilesResponse;
  projectTasks: Task[];
  projectMemories: MemoryItem[];
  projectTaskDraft: { goal: string; mode: string; scheduled_at: string; recurrence: string };
  projectMemoryDraft: string;
  activeProjectName: string | null;
  leftSidebarCollapsed: boolean;
  rightSidebarOpen: boolean;
  userMenuOpen: boolean;

  // --- computed values used by views ---
  isAdmin: boolean;
  selectedAgent: Agent | undefined;
  selectedWorkflow: import("../types").Workflow | null | undefined;
  activeProvider: Provider | null | undefined;
  activeModel: Model | null | undefined;
  activeSkills: Skill[];
  activeMcps: McpServer[];
  approximateTokens: number;
  activeTaskCount: number;
  paletteOpen: boolean;
  paletteSkills: Skill[];
  settingsTabDefs: Array<{ id: SettingsTab; label: string }>;
  adminSections: Array<{ id: AdminSection; label: string }>;
  settingsResults: Array<{ label: string; keywords: string; tab: SettingsTab; section?: AdminSection }>;
  filteredSkills: Skill[];

  // --- refs ---
  messageStackRef: RefObject<HTMLDivElement | null>;
  messageStackEndRef: RefObject<HTMLDivElement | null>;

  // --- setters used by view JSX ---
  setActiveView: (view: AppView) => void;
  setActiveConversationId: Dispatch<SetStateAction<number | null>>;
  setDraft: Dispatch<SetStateAction<string>>;
  setEditingMessageDraft: Dispatch<SetStateAction<string>>;
  setPaletteIndex: Dispatch<SetStateAction<number>>;
  setChatMode: Dispatch<SetStateAction<"act" | "plan" | "think">>;
  setSelectedWorkflowId: Dispatch<SetStateAction<string>>;
  setSelectedAgentId: Dispatch<SetStateAction<string>>;
  setSelectedAttachmentIds: Dispatch<SetStateAction<number[]>>;
  setTaskDraft: Dispatch<SetStateAction<{ goal: string; mode: string; scheduled_at: string; recurrence: string }>>;
  setExpandedTaskId: Dispatch<SetStateAction<number | null>>;
  setMemoryDraft: Dispatch<SetStateAction<{ content: string; kind: string }>>;
  setProjectDetail: Dispatch<SetStateAction<ProjectDetail | null>>;
  setProjectTab: Dispatch<SetStateAction<ProjectTab>>;
  setProjectDraft: Dispatch<SetStateAction<AppState["projectDraft"]>>;
  setProjectTaskDraft: Dispatch<SetStateAction<{ goal: string; mode: string; scheduled_at: string; recurrence: string }>>;
  setProjectMemoryDraft: Dispatch<SetStateAction<string>>;
  setProjectInstructionsDraft: Dispatch<SetStateAction<string>>;
  setHistorySearch: Dispatch<SetStateAction<string>>;
  setSettingsTab: Dispatch<SetStateAction<SettingsTab>>;
  setSettingsSection: Dispatch<SetStateAction<SettingsSection>>;
  setSettingsSearch: Dispatch<SetStateAction<string>>;
  setSkillTab: Dispatch<SetStateAction<SkillTab>>;
  setSkillSearch: Dispatch<SetStateAction<string>>;
  setSkillGeneratorPrompt: Dispatch<SetStateAction<string>>;
  setSkillDraft: Dispatch<SetStateAction<AppState["skillDraft"]>>;
  setInternetUrl: Dispatch<SetStateAction<string>>;
  setProviderDraft: Dispatch<SetStateAction<AppState["providerDraft"]>>;
  setModelDraft: Dispatch<SetStateAction<AppState["modelDraft"]>>;
  setAgentDraft: Dispatch<SetStateAction<AppState["agentDraft"]>>;
  setAgentEditDraft: Dispatch<SetStateAction<AppState["agentEditDraft"]>>;
  setAgentEditId: Dispatch<SetStateAction<number | null>>;
  setMcpDraft: Dispatch<SetStateAction<AppState["mcpDraft"]>>;
  setMcpRunDraft: Dispatch<SetStateAction<AppState["mcpRunDraft"]>>;
  setMcpInspection: Dispatch<SetStateAction<AppState["mcpInspection"]>>;
  setWorkflowDraft: Dispatch<SetStateAction<AppState["workflowDraft"]>>;
  setFallbackDraft: Dispatch<SetStateAction<AppState["fallbackDraft"]>>;
  setMetricsDays: Dispatch<SetStateAction<number>>;
  setAuditLogLimit: Dispatch<SetStateAction<number>>;
  setAuditFilters: Dispatch<SetStateAction<AppState["auditFilters"]>>;
  setMarketplaceDraft: Dispatch<SetStateAction<string>>;
  setConnectorTokenDrafts: Dispatch<SetStateAction<Record<string, string>>>;
  setPreferences: Dispatch<SetStateAction<Preferences | null>>;
  setGuardrailDraft: Dispatch<SetStateAction<GuardrailSettings>>;
  setTasksSettings: Dispatch<SetStateAction<TasksSettings>>;
  setWorkspaceDraft: Dispatch<SetStateAction<string>>;
  setUserMenuOpen: Dispatch<SetStateAction<boolean>>;
  setLeftSidebarCollapsed: Dispatch<SetStateAction<boolean>>;
  setRightSidebarOpen: Dispatch<SetStateAction<boolean>>;
  setError: Dispatch<SetStateAction<string>>;

  // --- handlers used by view JSX ---
  handleAuth: (event: FormEvent) => Promise<void>;
  logout: () => Promise<void>;
  createConversation: () => Promise<void>;
  deleteConversation: (conversation: Conversation) => Promise<void>;
  renameConversation: (conversation: Conversation) => Promise<void>;
  createFolder: () => Promise<void>;
  renameFolder: (folder: ChatFolder) => Promise<void>;
  deleteFolder: (folder: ChatFolder) => Promise<void>;
  moveConversation: (conversation: Conversation, folderId: number | null) => Promise<void>;
  toggleFolderExpanded: (folderId: number) => void;
  navButton: (view: AppView, label: string, short?: string, badge?: number) => ReactElement;
  openSettings: (section: SettingsSection) => void;
  sendMessage: (event: FormEvent) => Promise<void>;
  resumeApproval: (approval: PendingApproval, approved: boolean) => Promise<void>;
  decideHabitSuggestion: (suggestionId: number, decision: "accept" | "dismiss") => Promise<void>;
  saveEditMessage: (index: number) => void;
  cancelEditMessage: () => void;
  copyMessageText: (index: number) => void;
  startEditMessage: (index: number) => void;
  cycleChatMode: () => void;
  selectPaletteSkill: (skillName: string) => void;
  handleComposerKeyDown: (event: ReactKeyboardEvent<HTMLTextAreaElement>) => void;
  handleAttachmentUpload: (event: FormEvent<HTMLInputElement>) => Promise<void>;
  createTask: (event: FormEvent) => Promise<void>;
  taskAction: (taskId: number, action: "pause" | "resume" | "cancel") => Promise<void>;
  removeTask: (taskId: number) => Promise<void>;
  toggleTaskEvents: (taskId: number) => Promise<void>;
  decideTaskApproval: (approval: TaskApproval, approved: boolean) => Promise<void>;
  formatDateTime: (value: string) => string;
  createProject: (event: FormEvent) => Promise<void>;
  openProjectDetail: (projectId: number) => Promise<void>;
  archiveProject: (projectId: number, archived: boolean) => Promise<void>;
  removeProject: (projectId: number) => Promise<void>;
  createProjectChat: (projectId: number) => Promise<void>;
  projectLinkConversation: (projectId: number, conversationId: number, link: boolean) => Promise<void>;
  createProjectTask: (projectId: number, event: FormEvent) => Promise<void>;
  projectTaskAction: (projectId: number, taskId: number, action: "pause" | "resume" | "cancel") => Promise<void>;
  uploadProjectKnowledge: (projectId: number, event: FormEvent<HTMLInputElement>) => Promise<void>;
  projectLinkAttachment: (projectId: number, attachmentId: number, link: boolean) => Promise<void>;
  saveProjectInstructions: () => Promise<void>;
  addProjectMemory: (projectId: number, event: FormEvent) => Promise<void>;
  deleteProjectMemory: (projectId: number, memoryId: number) => Promise<void>;
  enableProjectWorkspace: (projectId: number) => Promise<void>;
  unlinkProjectWorkspace: (projectId: number) => Promise<void>;
  refreshProjectFiles: (projectId: number, subpath?: string) => Promise<void>;
  deleteProjectFile: (projectId: number, path: string, name: string, subpath: string) => Promise<void>;
  addMemory: (event: FormEvent) => Promise<void>;
  deleteMemory: (id: number) => Promise<void>;
  resetHabits: () => Promise<void>;
  testConnectorAccount: (connector: CatalogConnector) => Promise<void>;
  disconnectConnector: (connector: CatalogConnector) => Promise<void>;
  connectConnector: (slug: string) => Promise<void>;
  activateModel: (providerId: number, modelId: number) => Promise<void>;
  createProvider: (event: FormEvent) => Promise<void>;
  detectProviderModels: (providerId: number) => Promise<void>;
  toggleProvider: (provider: Provider, enabled: boolean) => Promise<void>;
  savePreferences: (updates: Partial<Preferences>) => Promise<void>;
  saveWorkspace: (event?: FormEvent) => Promise<void>;
  saveGuardrails: (event: FormEvent) => Promise<void>;
  saveTasksSettings: () => Promise<void>;
  createAgent: (event: FormEvent) => Promise<void>;
  editAgent: (agent: Agent) => void;
  saveAgentEdit: (agent: Agent, event: FormEvent) => Promise<void>;
  toggleAgent: (agent: Agent, enabled: boolean) => Promise<void>;
  toggleAgentAgentic: (agent: Agent, agenticMode: boolean) => Promise<void>;
  toggleAgentTool: (agentId: number, toolName: string, enabled: boolean) => Promise<void>;
  toggleAgentSkill: (agentId: number, skillId: number, enabled: boolean) => Promise<void>;
  toggleAgentMcp: (agentId: number, mcpServerId: number, enabled: boolean) => Promise<void>;
  addAgentFallback: (agentId: number) => Promise<void>;
  removeAgentFallback: (agentId: number, fallback: AgentFallback) => Promise<void>;
  createModel: (event: FormEvent) => Promise<void>;
  toggleModel: (model: Model, enabled: boolean) => Promise<void>;
  deleteModel: (model: Model) => Promise<void>;
  checkModel: (model: Model) => Promise<void>;
  createWorkflow: (event: FormEvent) => Promise<void>;
  toggleWorkflow: (workflow: import("../types").Workflow, enabled: boolean) => Promise<void>;
  createMcpServer: (event: FormEvent) => Promise<void>;
  validateMcpServer: () => Promise<void>;
  runMcpServer: (event: FormEvent) => Promise<void>;
  toggleMcpServer: (server: McpServer, enabled: boolean) => Promise<void>;
  inspectMcpServer: (server: McpServer) => Promise<void>;
  deleteMcpServer: (server: McpServer) => Promise<void>;
  installPluginEntry: (entry: import("../types").PluginCatalogEntry) => Promise<void>;
  uninstallPluginEntry: (entry: import("../types").PluginCatalogEntry) => Promise<void>;
  addPluginMarketplace: (event: FormEvent) => Promise<void>;
  refreshPluginMarketplace: (name: string) => Promise<void>;
  removePluginMarketplace: (name: string) => Promise<void>;
  missingConnectorsFor: (entry: import("../types").PluginCatalogEntry) => string[];
  updateUserRole: (userId: number, role: "admin" | "user") => Promise<void>;
  refreshWorkspace: () => Promise<void>;
  formatAuditMetadata: (metadata: Record<string, unknown>) => string;
  createSkill: (event: FormEvent) => Promise<void>;
  editSkill: (skill: Skill) => void;
  resetSkillEditor: () => void;
  toggleSkill: (skill: Skill, enabled: boolean) => Promise<void>;
  deleteSkill: (skill: Skill) => Promise<void>;
  generateSkillDraft: (event: FormEvent) => Promise<void>;
  useGeneratedSkill: () => void;
  runReadUrl: (event: FormEvent) => Promise<void>;
  skillAgents: (skillId: number) => Agent[];
  loadMetrics: (days: number) => Promise<void>;
  deleteAttachment: (attachment: Attachment) => Promise<void>;
}

export const AppStateContext = createContext<AppState | null>(null);

export function useApp(): AppState {
  const context = useContext(AppStateContext);
  if (!context) {
    throw new Error("useApp must be used within AppStateContext.Provider");
  }
  return context;
}
