-- ObsyGPT database schema — GENERATED from Alembic migrations (source of truth: backend/migrations).
-- Regenerate with: cd backend && python -m alembic upgrade head --sql > ..\database\schema.sql
-- Do not edit by hand; make changes as new Alembic migrations.

En línea: 1 Carácter: 87
+ ... 2/obsygpt'; & venv\Scripts\python.exe -m alembic upgrade head --sql 2 ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (INFO  [alembic....PostgresqlImpl.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 0001_initial_obsygpt

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    username VARCHAR(50) NOT NULL, 
    email VARCHAR(255) NOT NULL, 
    role VARCHAR(20) DEFAULT 'user' NOT NULL, 
    password_hash TEXT NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    CHECK (role IN ('admin', 'user')), 
    UNIQUE (username), 
    UNIQUE (email)
);

CREATE TABLE providers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    name VARCHAR(100) NOT NULL, 
    provider_type VARCHAR(50) NOT NULL, 
    base_url TEXT, 
    api_key_env VARCHAR(100), 
    enabled BOOLEAN DEFAULT true NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    UNIQUE (name)
);

CREATE TABLE models (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    provider_id INTEGER NOT NULL, 
    model_name VARCHAR(200) NOT NULL, 
    display_name VARCHAR(200) NOT NULL, 
    supports_text BOOLEAN DEFAULT true NOT NULL, 
    supports_streaming BOOLEAN DEFAULT true NOT NULL, 
    supports_vision BOOLEAN DEFAULT false NOT NULL, 
    supports_audio BOOLEAN DEFAULT false NOT NULL, 
    supports_tools BOOLEAN DEFAULT false NOT NULL, 
    supports_json BOOLEAN DEFAULT false NOT NULL, 
    context_window INTEGER, 
    enabled BOOLEAN DEFAULT true NOT NULL, 
    PRIMARY KEY (id), 
    UNIQUE (provider_id, model_name), 
    FOREIGN KEY(provider_id) REFERENCES providers (id) ON DELETE CASCADE
);

CREATE TABLE conversations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    user_id INTEGER NOT NULL, 
    title VARCHAR(100) DEFAULT 'New Chat' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    conversation_id INTEGER NOT NULL, 
    role VARCHAR(20) NOT NULL, 
    content TEXT NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    CHECK (role IN ('user', 'assistant')), 
    FOREIGN KEY(conversation_id) REFERENCES conversations (id) ON DELETE CASCADE
);

CREATE TABLE agents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    name VARCHAR(100) NOT NULL, 
    description TEXT DEFAULT '' NOT NULL, 
    system_prompt TEXT NOT NULL, 
    provider_id INTEGER, 
    model_id INTEGER, 
    temperature NUMERIC(3, 2) DEFAULT '0.70' NOT NULL, 
    internet_enabled BOOLEAN DEFAULT false NOT NULL, 
    multimodal_enabled BOOLEAN DEFAULT false NOT NULL, 
    enabled BOOLEAN DEFAULT true NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    UNIQUE (name), 
    FOREIGN KEY(provider_id) REFERENCES providers (id) ON DELETE SET NULL, 
    FOREIGN KEY(model_id) REFERENCES models (id) ON DELETE SET NULL
);

CREATE TABLE skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    name VARCHAR(100) NOT NULL, 
    description TEXT DEFAULT '' NOT NULL, 
    enabled BOOLEAN DEFAULT true NOT NULL, 
    PRIMARY KEY (id), 
    UNIQUE (name)
);

CREATE TABLE agent_skills (
    agent_id INTEGER NOT NULL, 
    skill_id INTEGER NOT NULL, 
    PRIMARY KEY (agent_id, skill_id), 
    FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE, 
    FOREIGN KEY(skill_id) REFERENCES skills (id) ON DELETE CASCADE
);

CREATE TABLE mcp_servers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    name VARCHAR(100) NOT NULL, 
    description TEXT DEFAULT '' NOT NULL, 
    connection_type VARCHAR(20) NOT NULL, 
    command TEXT, 
    url TEXT, 
    enabled BOOLEAN DEFAULT false NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    CHECK (connection_type IN ('command', 'url')), 
    UNIQUE (name)
);

CREATE TABLE agent_mcps (
    agent_id INTEGER NOT NULL, 
    mcp_server_id INTEGER NOT NULL, 
    PRIMARY KEY (agent_id, mcp_server_id), 
    FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE, 
    FOREIGN KEY(mcp_server_id) REFERENCES mcp_servers (id) ON DELETE CASCADE
);

CREATE TABLE workflows (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    name VARCHAR(100) NOT NULL, 
    workflow_type VARCHAR(30) NOT NULL, 
    enabled BOOLEAN DEFAULT true NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    CHECK (workflow_type IN ('single_agent', 'sequential', 'supervisor', 'reviewer', 'parallel', 'debate')), 
    UNIQUE (name)
);

CREATE TABLE workflow_steps (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    workflow_id INTEGER NOT NULL, 
    agent_id INTEGER, 
    step_order INTEGER NOT NULL, 
    step_name VARCHAR(100) NOT NULL, 
    PRIMARY KEY (id), 
    UNIQUE (workflow_id, step_order), 
    FOREIGN KEY(workflow_id) REFERENCES workflows (id) ON DELETE CASCADE, 
    FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE SET NULL
);

CREATE TABLE agent_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    user_id INTEGER NOT NULL, 
    conversation_id INTEGER NOT NULL, 
    message_id INTEGER, 
    agent_id INTEGER, 
    workflow_id INTEGER, 
    status VARCHAR(20) NOT NULL, 
    final_response TEXT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    completed_at TIMESTAMP WITH TIME ZONE, 
    PRIMARY KEY (id), 
    CHECK (status IN ('running', 'completed', 'failed')), 
    FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
    FOREIGN KEY(conversation_id) REFERENCES conversations (id) ON DELETE CASCADE, 
    FOREIGN KEY(message_id) REFERENCES messages (id) ON DELETE SET NULL, 
    FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE SET NULL, 
    FOREIGN KEY(workflow_id) REFERENCES workflows (id) ON DELETE SET NULL
);

CREATE TABLE agent_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    agent_run_id INTEGER NOT NULL, 
    event_type VARCHAR(50) NOT NULL, 
    title VARCHAR(200) NOT NULL, 
    content TEXT DEFAULT '' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(agent_run_id) REFERENCES agent_runs (id) ON DELETE CASCADE
);

CREATE TABLE tool_calls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    agent_run_id INTEGER NOT NULL, 
    skill_name VARCHAR(100) NOT NULL, 
    input_summary TEXT DEFAULT '' NOT NULL, 
    output_summary TEXT DEFAULT '' NOT NULL, 
    status VARCHAR(20) NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    CHECK (status IN ('running', 'completed', 'failed')), 
    FOREIGN KEY(agent_run_id) REFERENCES agent_runs (id) ON DELETE CASCADE
);

CREATE TABLE mcp_calls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    agent_run_id INTEGER NOT NULL, 
    mcp_server_id INTEGER, 
    tool_name VARCHAR(100) NOT NULL, 
    input_summary TEXT DEFAULT '' NOT NULL, 
    output_summary TEXT DEFAULT '' NOT NULL, 
    status VARCHAR(20) NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    CHECK (status IN ('running', 'completed', 'failed')), 
    FOREIGN KEY(agent_run_id) REFERENCES agent_runs (id) ON DELETE CASCADE, 
    FOREIGN KEY(mcp_server_id) REFERENCES mcp_servers (id) ON DELETE SET NULL
);

CREATE TABLE attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    user_id INTEGER NOT NULL, 
    message_id INTEGER, 
    file_name TEXT NOT NULL, 
    mime_type VARCHAR(150) NOT NULL, 
    storage_path TEXT NOT NULL, 
    size_bytes INTEGER NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
    FOREIGN KEY(message_id) REFERENCES messages (id) ON DELETE CASCADE
);

CREATE TABLE artifacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    agent_run_id INTEGER, 
    attachment_id INTEGER, 
    artifact_type VARCHAR(50) NOT NULL, 
    title VARCHAR(200) NOT NULL, 
    content TEXT NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(agent_run_id) REFERENCES agent_runs (id) ON DELETE CASCADE, 
    FOREIGN KEY(attachment_id) REFERENCES attachments (id) ON DELETE CASCADE
);

CREATE TABLE sources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    agent_run_id INTEGER, 
    url TEXT NOT NULL, 
    title TEXT DEFAULT '' NOT NULL, 
    snippet TEXT DEFAULT '' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(agent_run_id) REFERENCES agent_runs (id) ON DELETE CASCADE
);

CREATE TABLE settings (
    key VARCHAR(100) NOT NULL, 
    value TEXT NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (key)
);

INSERT INTO providers (name, provider_type, base_url, api_key_env, enabled) VALUES
        ('OpenRouter', 'openrouter', 'https://openrouter.ai/api/v1', 'OPENROUTER_API_KEY', true),
        ('OpenAI', 'openai', 'https://api.openai.com/v1', 'OPENAI_API_KEY', false),
        ('Anthropic', 'anthropic', 'https://api.anthropic.com', 'ANTHROPIC_API_KEY', false),
        ('Gemini', 'gemini', 'https://generativelanguage.googleapis.com', 'GEMINI_API_KEY', false),
        ('Ollama', 'ollama', 'http://127.0.0.1:11434/v1', NULL, false),
        ('llama.cpp', 'llamacpp', 'http://127.0.0.1:8080/v1', NULL, false),
        ('Custom OpenAI-Compatible', 'openai_compatible', NULL, NULL, false);;

INSERT INTO models (provider_id, model_name, display_name, supports_text, supports_streaming, supports_vision, supports_audio, supports_tools, supports_json, context_window, enabled)
    SELECT p.id, seed.model_name, seed.display_name, seed.supports_text, seed.supports_streaming, seed.supports_vision, seed.supports_audio, seed.supports_tools, seed.supports_json, seed.context_window, seed.enabled
    FROM providers p
    JOIN (VALUES
        ('OpenRouter', 'nvidia/nemotron-3-super-120b-a12b:free', 'NVIDIA Nemotron 3 Super 120B', true, true, false, false, false, false, NULL::integer, true),
        ('OpenAI', 'gpt-4.1-mini', 'GPT-4.1 Mini', true, true, true, true, true, true, 1047576, false),
        ('Anthropic', 'claude-3-5-sonnet-latest', 'Claude 3.5 Sonnet', true, true, true, false, true, false, 200000, false),
        ('Gemini', 'gemini-1.5-pro', 'Gemini 1.5 Pro', true, true, true, true, true, true, 2000000, false),
        ('Ollama', 'llama3.1', 'Ollama llama3.1', true, true, false, false, false, true, NULL::integer, false),
        ('llama.cpp', 'local-model', 'llama.cpp local model', true, true, false, false, false, true, NULL::integer, false)
    ) AS seed(provider_name, model_name, display_name, supports_text, supports_streaming, supports_vision, supports_audio, supports_tools, supports_json, context_window, enabled)
    ON p.name = seed.provider_name;;

INSERT INTO skills (name, description, enabled) VALUES
        ('web_search', 'Search the web and return ranked results.', true),
        ('read_url', 'Read and extract clean content from a URL.', true),
        ('extract_pdf', 'Extract text and metadata from uploaded PDFs.', true),
        ('summarize_document', 'Summarize extracted document content.', true),
        ('analyze_image', 'Analyze an uploaded image with a vision-capable model.', true),
        ('critic_review', 'Review an intermediate answer for quality and accuracy.', true),
        ('final_answer', 'Synthesize a final user-facing answer.', true);;

INSERT INTO agents (name, description, system_prompt, provider_id, model_id, internet_enabled, multimodal_enabled, enabled)
    SELECT 'Default Assistant', 'Default ObsyGPT text assistant.', 'You are ObsyGPT, a helpful multi-agent AI assistant. Answer clearly and accurately.', p.id, m.id, false, false, true
    FROM providers p JOIN models m ON m.provider_id = p.id
    WHERE p.name = 'OpenRouter' AND m.model_name = 'nvidia/nemotron-3-super-120b-a12b:free';
    INSERT INTO agents (name, description, system_prompt, provider_id, model_id, internet_enabled, multimodal_enabled, enabled)
    SELECT seed.name, seed.description, seed.system_prompt, p.id, m.id, seed.internet_enabled, seed.multimodal_enabled, true
    FROM providers p JOIN models m ON m.provider_id = p.id
    JOIN (VALUES
        ('Research Agent', 'Finds useful context and source leads.', 'You are ObsyGPT Research Agent. Identify useful facts, gaps, and source leads. Be concise.', true, false),
        ('Writer Agent', 'Drafts clear final answers.', 'You are ObsyGPT Writer Agent. Turn the available context into a clear answer for the user.', false, false),
        ('Critic Agent', 'Reviews answers for accuracy and omissions.', 'You are ObsyGPT Critic Agent. Improve accuracy, identify missing caveats, and return a corrected final answer.', false, false)
    ) AS seed(name, description, system_prompt, internet_enabled, multimodal_enabled)
    ON p.name = 'OpenRouter' AND m.model_name = 'nvidia/nemotron-3-super-120b-a12b:free';;

INSERT INTO workflows (name, workflow_type, enabled) VALUES
        ('Default Single Agent', 'single_agent', true),
        ('Research Then Write', 'sequential', true),
        ('Writer With Critic', 'reviewer', true),
        ('Parallel Draft Review', 'parallel', true),
        ('Debate Then Judge', 'debate', true);
    INSERT INTO workflow_steps (workflow_id, agent_id, step_order, step_name)
    SELECT w.id, a.id, seed.step_order, seed.step_name
    FROM workflows w
    JOIN (VALUES
        ('Research Then Write', 'Research Agent', 1, 'Research'),
        ('Research Then Write', 'Writer Agent', 2, 'Write'),
        ('Writer With Critic', 'Writer Agent', 1, 'Draft'),
        ('Writer With Critic', 'Critic Agent', 2, 'Review'),
        ('Parallel Draft Review', 'Research Agent', 1, 'Research'),
        ('Parallel Draft Review', 'Writer Agent', 2, 'Draft'),
        ('Parallel Draft Review', 'Critic Agent', 3, 'Critique'),
        ('Debate Then Judge', 'Research Agent', 1, 'Position A'),
        ('Debate Then Judge', 'Writer Agent', 2, 'Position B'),
        ('Debate Then Judge', 'Critic Agent', 3, 'Judge')
    ) AS seed(workflow_name, agent_name, step_order, step_name) ON w.name = seed.workflow_name
    JOIN agents a ON a.name = seed.agent_name;
    INSERT INTO agent_skills (agent_id, skill_id)
    SELECT a.id, s.id
    FROM agents a
    JOIN (VALUES
        ('Research Agent', 'read_url'),
        ('Research Agent', 'web_search'),
        ('Critic Agent', 'critic_review'),
        ('Writer Agent', 'final_answer'),
        ('Default Assistant', 'final_answer')
    ) AS seed(agent_name, skill_name) ON a.name = seed.agent_name
    JOIN skills s ON s.name = seed.skill_name;;

INSERT INTO alembic_version (version_num) VALUES ('0001_initial_obsygpt') RETURNING alembic_version.version_num;

-- Running upgrade 0001_initial_obsygpt -> 0002_audit_logs

CREATE TABLE audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    actor_user_id INTEGER, 
    action VARCHAR(100) NOT NULL, 
    target_type VARCHAR(100) NOT NULL, 
    target_id INTEGER, 
    metadata JSON DEFAULT '{}'::json NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(actor_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_audit_logs_actor_user_id ON audit_logs (actor_user_id);

CREATE INDEX ix_audit_logs_action ON audit_logs (action);

CREATE INDEX ix_audit_logs_target ON audit_logs (target_type, target_id);

UPDATE alembic_version SET version_num='0002_audit_logs' WHERE alembic_version.version_num = '0001_initial_obsygpt';

standard fields.
-- Running upgrade 0002_audit_logs -> 0003_agent_skill_standard

ALTER TABLE skills ADD COLUMN argument_hint TEXT DEFAULT '' NOT NULL;

ALTER TABLE skills ADD COLUMN triggers VARCHAR(20)[] DEFAULT ARRAY['user']::varchar[] NOT NULL;

ALTER TABLE skills ADD COLUMN body TEXT DEFAULT '# Instrucciones principales
1. Describe el flujo de trabajo de la skill.

## Restricciones
* No ejecutes acciones destructivas sin confirmacion explicita.' NOT NULL;

ALTER TABLE skills ADD COLUMN resources TEXT DEFAULT '' NOT NULL;

UPDATE alembic_version SET version_num='0003_agent_skill_standard' WHERE alembic_version.version_num = '0002_audit_logs';

-- Running upgrade 0003_agent_skill_standard -> 0004_seed_standard_skill_bodies

standard SKILL.md content for built-in skills.
UPDATE skills
            SET argument_hint = 'Search query and optional result constraints.',
                triggers = ARRAY['user','model']::varchar[],
                body = $body$# Instrucciones principales
1. Convierte la tarea del usuario en una consulta de busqueda concreta.
2. Prioriza fuentes recientes, oficiales o verificables.
3. Resume los resultados por relevancia e incluye enlaces cuando existan.
4. Senala incertidumbre, fechas y posibles sesgos de las fuentes.

## Restricciones
* No inventes URLs, titulos ni datos.
* No uses busqueda web para informacion sensible si el usuario no lo pidio.
* No presentes resultados no verificados como hechos definitivos.$body$,
                resources = 'examples/search-query.md'
            WHERE name = 'web_search';;

UPDATE skills
            SET argument_hint = 'URL publica para leer y sintetizar.',
                triggers = ARRAY['user','model']::varchar[],
                body = $body$# Instrucciones principales
1. Valida que la entrada contiene una URL publica.
2. Extrae el contenido principal y descarta navegacion, anuncios y boilerplate.
3. Devuelve un resumen fiel, puntos clave y cualquier dato accionable.
4. Cita la URL original en la respuesta.

## Restricciones
* No leas URLs privadas, locales o potencialmente internas.
* No inventes contenido que no aparezca en la pagina.
* Si la pagina no se puede leer, explica el fallo y pide otra fuente.$body$,
                resources = 'examples/read-url.md'
            WHERE name = 'read_url';;

UPDATE skills
            SET argument_hint = 'PDF adjunto o referencia a un archivo ya subido.',
                triggers = ARRAY['user']::varchar[],
                body = $body$# Instrucciones principales
1. Identifica el PDF adjunto que el usuario quiere procesar.
2. Extrae texto, metadatos visibles y estructura basica del documento.
3. Conserva secciones, tablas o paginas relevantes cuando sea posible.
4. Devuelve un resultado organizado por pagina o seccion.

## Restricciones
* No asumas texto que no se haya extraido.
* Si el PDF esta escaneado o incompleto, indicalo claramente.
* No expongas datos sensibles salvo que sean necesarios para la tarea.$body$,
                resources = 'examples/pdf-extraction.md'
            WHERE name = 'extract_pdf';;

UPDATE skills
            SET argument_hint = 'Texto extraido, documento adjunto o seleccion de contenido.',
                triggers = ARRAY['user','model']::varchar[],
                body = $body$# Instrucciones principales
1. Identifica objetivo, audiencia y extension deseada del resumen.
2. Resume tesis principal, puntos clave, decisiones, riesgos y siguientes pasos.
3. Mantiene la terminologia del documento original.
4. Incluye una seccion de dudas o informacion faltante si aplica.

## Restricciones
* No cambies el sentido del documento.
* No anadas conclusiones que no esten respaldadas por el contenido.
* No ocultes contradicciones o limitaciones importantes.$body$,
                resources = 'templates/document-summary.md'
            WHERE name = 'summarize_document';;

UPDATE skills
            SET argument_hint = 'Imagen adjunta y pregunta concreta sobre la imagen.',
                triggers = ARRAY['user']::varchar[],
                body = $body$# Instrucciones principales
1. Describe primero los elementos visuales observables.
2. Responde la pregunta del usuario usando solo evidencia visible.
3. Diferencia observaciones de inferencias.
4. Si hace falta OCR, transcribe el texto visible y marca baja confianza.

## Restricciones
* No identifiques personas reales ni atributos sensibles.
* No afirmes detalles no visibles.
* No uses analisis de imagen si el modelo activo no soporta vision.$body$,
                resources = 'examples/image-analysis.md'
            WHERE name = 'analyze_image';;

UPDATE skills
            SET argument_hint = 'Borrador o respuesta intermedia a revisar.',
                triggers = ARRAY['user','model']::varchar[],
                body = $body$# Instrucciones principales
1. Evalua exactitud, completitud, claridad y riesgos de la respuesta.
2. Identifica afirmaciones no justificadas, contradicciones y omisiones.
3. Propone correcciones concretas y priorizadas.
4. Devuelve una version revisada si el usuario lo pide.

## Restricciones
* No reescribas por estilo si hay errores factuales sin resolver.
* No suavices riesgos importantes.
* No apruebes una respuesta si faltan evidencias clave.$body$,
                resources = 'templates/critic-review.md'
            WHERE name = 'critic_review';;

UPDATE skills
            SET argument_hint = 'Contexto, hallazgos y borradores previos.',
                triggers = ARRAY['user','model']::varchar[],
                body = $body$# Instrucciones principales
1. Integra contexto, resultados de agentes y restricciones del usuario.
2. Produce una respuesta final clara, accionable y directamente util.
3. Ordena la respuesta de lo mas importante a lo accesorio.
4. Incluye supuestos, limites y siguientes pasos solo cuando aporten valor.

## Restricciones
* No incluyas trazas internas ni razonamiento privado.
* No cites fuentes o herramientas que no se hayan usado.
* No inventes consenso si los agentes discrepan.$body$,
                resources = 'templates/final-answer.md'
            WHERE name = 'final_answer';;

UPDATE alembic_version SET version_num='0004_seed_standard_skill_bodies' WHERE alembic_version.version_num = '0003_agent_skill_standard';

tables
-- Running upgrade 0004_seed_standard_skill_bodies -> 0005_agent_loop

ALTER TABLE agents ADD COLUMN agentic_mode BOOLEAN DEFAULT false NOT NULL;

CREATE TABLE agent_tool_permissions (
    agent_id INTEGER NOT NULL, 
    tool_name VARCHAR(100) NOT NULL, 
    allowed BOOLEAN DEFAULT true NOT NULL, 
    PRIMARY KEY (agent_id, tool_name), 
    FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE
);

CREATE TABLE tool_approvals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    agent_run_id INTEGER NOT NULL, 
    user_id INTEGER NOT NULL, 
    conversation_id INTEGER NOT NULL, 
    tool_name VARCHAR(100) NOT NULL, 
    args JSON DEFAULT '{}'::json NOT NULL, 
    status VARCHAR(20) DEFAULT 'pending' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    decided_at TIMESTAMP WITH TIME ZONE, 
    PRIMARY KEY (id), 
    FOREIGN KEY(agent_run_id) REFERENCES agent_runs (id) ON DELETE CASCADE, 
    FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
    FOREIGN KEY(conversation_id) REFERENCES conversations (id) ON DELETE CASCADE
);

CREATE INDEX ix_tool_approvals_pending ON tool_approvals (status, user_id);

CREATE TABLE agent_run_state (
    agent_run_id INTEGER NOT NULL, 
    messages JSON DEFAULT '[]'::json NOT NULL, 
    iterations INTEGER DEFAULT 0 NOT NULL, 
    tool_call_count INTEGER DEFAULT 0 NOT NULL, 
    thought_text TEXT DEFAULT '' NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (agent_run_id), 
    FOREIGN KEY(agent_run_id) REFERENCES agent_runs (id) ON DELETE CASCADE
);

CREATE TABLE app_settings (
    key VARCHAR(100) NOT NULL, 
    value JSON DEFAULT '{}'::json NOT NULL, 
    PRIMARY KEY (key)
);

INSERT INTO app_settings (key, value)
        VALUES (
            'guardrails',
            '{"max_iterations": 12, "max_tool_calls": 25, "max_duration_seconds": 180, "max_tool_output_chars": 10000, "max_total_chars": 50000, "loop_repeat_limit": 3}'::json
        )
        ON CONFLICT (key) DO NOTHING;;

INSERT INTO agent_tool_permissions (agent_id, tool_name, allowed)
        SELECT a.id, seed.tool_name, true
        FROM agents a
        CROSS JOIN (VALUES
            ('read_file'),
            ('list_dir'),
            ('web_fetch')
        ) AS seed(tool_name)
        ON CONFLICT (agent_id, tool_name) DO NOTHING;;

UPDATE alembic_version SET version_num='0005_agent_loop' WHERE alembic_version.version_num = '0004_seed_standard_skill_bodies';

-- Running upgrade 0005_agent_loop -> 0006_memory_habits

CREATE TABLE memories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    user_id INTEGER NOT NULL, 
    kind VARCHAR(20) DEFAULT 'memory' NOT NULL, 
    content TEXT NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_memories_user_kind ON memories (user_id, kind);

UPDATE alembic_version SET version_num='0006_memory_habits' WHERE alembic_version.version_num = '0005_agent_loop';

-- Running upgrade 0006_memory_habits -> 0007_agent_fallbacks

CREATE TABLE agent_fallbacks (
    agent_id INTEGER NOT NULL, 
    provider_id INTEGER NOT NULL, 
    model_id INTEGER NOT NULL, 
    priority INTEGER NOT NULL, 
    PRIMARY KEY (agent_id, priority), 
    FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE, 
    FOREIGN KEY(provider_id) REFERENCES providers (id) ON DELETE CASCADE, 
    FOREIGN KEY(model_id) REFERENCES models (id) ON DELETE CASCADE
);

UPDATE alembic_version SET version_num='0007_agent_fallbacks' WHERE alembic_version.version_num = '0006_memory_habits';

task events, user settings, task approvals
-- Running upgrade 0007_agent_fallbacks -> 0008_tasks_workspace

CREATE TABLE tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    user_id INTEGER NOT NULL, 
    goal TEXT NOT NULL, 
    mode VARCHAR(10) DEFAULT 'act' NOT NULL, 
    status VARCHAR(30) DEFAULT 'pending' NOT NULL, 
    scheduled_at TIMESTAMP WITH TIME ZONE, 
    attempts INTEGER DEFAULT 0 NOT NULL, 
    next_attempt_at TIMESTAMP WITH TIME ZONE, 
    agent_id INTEGER, 
    result TEXT DEFAULT '' NOT NULL, 
    error TEXT DEFAULT '' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
    FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE SET NULL
);

CREATE INDEX ix_tasks_user_status ON tasks (user_id, status);

CREATE TABLE task_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    task_id INTEGER NOT NULL, 
    event_type VARCHAR(50) NOT NULL, 
    title VARCHAR(200) NOT NULL, 
    content TEXT DEFAULT '' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(task_id) REFERENCES tasks (id) ON DELETE CASCADE
);

CREATE INDEX ix_task_events_task ON task_events (task_id);

CREATE TABLE user_settings (
    user_id INTEGER NOT NULL, 
    key VARCHAR(100) NOT NULL, 
    value JSON DEFAULT '{}'::json NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (user_id, key), 
    FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

ALTER TABLE agent_runs ALTER COLUMN conversation_id DROP NOT NULL;

ALTER TABLE tool_approvals ALTER COLUMN conversation_id DROP NOT NULL;

ALTER TABLE tool_approvals ADD COLUMN task_id INTEGER;

ALTER TABLE tool_approvals ADD FOREIGN KEY(task_id) REFERENCES tasks (id) ON DELETE CASCADE;

INSERT INTO app_settings (key, value)
        VALUES ('tasks', '{"max_concurrent_tasks": 1, "auto_resume_tasks": true}'::json)
        ON CONFLICT (key) DO NOTHING;;

UPDATE alembic_version SET version_num='0008_tasks_workspace' WHERE alembic_version.version_num = '0007_agent_fallbacks';

conversations and attachments
-- Running upgrade 0008_tasks_workspace -> 0009_projects

CREATE TABLE projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    user_id INTEGER NOT NULL, 
    name VARCHAR(120) NOT NULL, 
    description TEXT DEFAULT '' NOT NULL, 
    instructions TEXT DEFAULT '' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_projects_user ON projects (user_id);

CREATE TABLE project_conversations (
    project_id INTEGER NOT NULL, 
    conversation_id INTEGER NOT NULL, 
    PRIMARY KEY (project_id, conversation_id), 
    FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE, 
    FOREIGN KEY(conversation_id) REFERENCES conversations (id) ON DELETE CASCADE
);

CREATE TABLE project_attachments (
    project_id INTEGER NOT NULL, 
    attachment_id INTEGER NOT NULL, 
    PRIMARY KEY (project_id, attachment_id), 
    FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE, 
    FOREIGN KEY(attachment_id) REFERENCES attachments (id) ON DELETE CASCADE
);

UPDATE alembic_version SET version_num='0009_projects' WHERE alembic_version.version_num = '0008_tasks_workspace';

context, archive, project tasks and memory
-- Running upgrade 0009_projects -> 0010_cowork_projects

ALTER TABLE projects ADD COLUMN folder_path TEXT;

ALTER TABLE projects ADD COLUMN archived BOOLEAN DEFAULT false NOT NULL;

ALTER TABLE tasks ADD COLUMN project_id INTEGER;

ALTER TABLE tasks ADD FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE SET NULL;

ALTER TABLE tasks ADD COLUMN recurrence VARCHAR(20);

ALTER TABLE tasks ADD COLUMN last_occurrence_at TIMESTAMP WITH TIME ZONE;

CREATE INDEX ix_tasks_project ON tasks (project_id);

ALTER TABLE memories ADD COLUMN project_id INTEGER;

ALTER TABLE memories ADD FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE;

CREATE INDEX ix_memories_project ON memories (project_id);

UPDATE alembic_version SET version_num='0010_cowork_projects' WHERE alembic_version.version_num = '0009_projects';

-- Running upgrade 0010_cowork_projects -> 0011_habit_suggestions

habit_suggestions for user-approved habit learning.
CREATE TABLE habit_suggestions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    user_id INTEGER NOT NULL, 
    content TEXT NOT NULL, 
    evidence TEXT DEFAULT '' NOT NULL, 
    source VARCHAR(20) DEFAULT 'model' NOT NULL, 
    status VARCHAR(20) DEFAULT 'pending' NOT NULL, 
    conversation_id INTEGER, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    decided_at TIMESTAMP WITH TIME ZONE, 
    PRIMARY KEY (id), 
    FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_habit_suggestions_user_status ON habit_suggestions (user_id, status);

UPDATE alembic_version SET version_num='0011_habit_suggestions' WHERE alembic_version.version_num = '0010_cowork_projects';

without an agent run for manual admin executions.
-- Running upgrade 0011_habit_suggestions -> 0012_mcp_calls_nullable

ALTER TABLE mcp_calls ALTER COLUMN agent_run_id DROP NOT NULL;

UPDATE alembic_version SET version_num='0012_mcp_calls_nullable' WHERE alembic_version.version_num = '0011_habit_suggestions';

-- Running upgrade 0012_mcp_calls_nullable -> 0013_connectors

and user connector accounts.
CREATE TABLE connectors (
    slug VARCHAR(50) NOT NULL, 
    name VARCHAR(100) NOT NULL, 
    description TEXT DEFAULT '' NOT NULL, 
    auth_type VARCHAR(20) DEFAULT 'token' NOT NULL, 
    token_label VARCHAR(200) DEFAULT '' NOT NULL, 
    enabled BOOLEAN DEFAULT true NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (slug)
);

CREATE TABLE connector_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    user_id INTEGER NOT NULL, 
    connector_slug VARCHAR(50) NOT NULL, 
    credentials_encrypted TEXT NOT NULL, 
    display_name TEXT DEFAULT '' NOT NULL, 
    status VARCHAR(20) DEFAULT 'connected' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT uq_connector_accounts_user_slug UNIQUE (user_id, connector_slug), 
    FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
    FOREIGN KEY(connector_slug) REFERENCES connectors (slug) ON DELETE CASCADE
);

INSERT INTO connectors (slug, name, description, auth_type, token_label, enabled) VALUES
        ('github', 'GitHub', 'Buscar repos, leer archivos e issues, y crear issues en nombre del usuario.', 'token', 'Personal access token (PAT)', true),
        ('gdrive', 'Google Drive', 'Buscar archivos y leer documentos de Google Drive del usuario (solo lectura).', 'token', 'OAuth access token', true);;

UPDATE alembic_version SET version_num='0013_connectors' WHERE alembic_version.version_num = '0012_mcp_calls_nullable';

-- Running upgrade 0013_connectors -> 0014_plugins

installed plugins.
CREATE TABLE plugin_marketplaces (
    name VARCHAR(100) NOT NULL, 
    url TEXT NOT NULL, 
    added_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (name), 
    UNIQUE (url)
);

CREATE TABLE plugins (
    slug VARCHAR(80) NOT NULL, 
    name VARCHAR(150) NOT NULL, 
    version VARCHAR(30) DEFAULT '1.0.0' NOT NULL, 
    description TEXT DEFAULT '' NOT NULL, 
    source VARCHAR(20) DEFAULT 'local' NOT NULL, 
    marketplace_name VARCHAR(100), 
    manifest JSON NOT NULL, 
    installed_refs JSON NOT NULL, 
    installed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (slug), 
    FOREIGN KEY(marketplace_name) REFERENCES plugin_marketplaces (name) ON DELETE SET NULL
);

UPDATE alembic_version SET version_num='0014_plugins' WHERE alembic_version.version_num = '0013_connectors';

parent run linkage and dispatch registry.
-- Running upgrade 0014_plugins -> 0015_subagents

ALTER TABLE agent_runs ADD COLUMN parent_run_id INTEGER;

ALTER TABLE agent_runs ADD FOREIGN KEY(parent_run_id) REFERENCES agent_runs (id) ON DELETE CASCADE;

CREATE INDEX ix_agent_runs_parent ON agent_runs (parent_run_id);

CREATE TABLE subagent_dispatches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    parent_run_id INTEGER NOT NULL, 
    child_run_id INTEGER NOT NULL, 
    agent_name VARCHAR(100) NOT NULL, 
    goal TEXT NOT NULL, 
    status VARCHAR(20) DEFAULT 'pending' NOT NULL, 
    result TEXT DEFAULT '' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(parent_run_id) REFERENCES agent_runs (id) ON DELETE CASCADE, 
    UNIQUE (child_run_id), 
    FOREIGN KEY(child_run_id) REFERENCES agent_runs (id) ON DELETE CASCADE
);

CREATE INDEX ix_subagent_dispatches_parent ON subagent_dispatches (parent_run_id);

UPDATE alembic_version SET version_num='0015_subagents' WHERE alembic_version.version_num = '0014_plugins';

-- Running upgrade 0015_subagents -> 0016_agent_runs_awaiting

ALTER TABLE agent_runs DROP CONSTRAINT agent_runs_status_check;;

status on agent_runs.
ALTER TABLE agent_runs ADD CONSTRAINT agent_runs_status_check CHECK (status IN ('running', 'completed', 'failed', 'awaiting_approval'));;

UPDATE alembic_version SET version_num='0016_agent_runs_awaiting' WHERE alembic_version.version_num = '0015_subagents';

-- Running upgrade 0016_agent_runs_awaiting -> 0017_chat_folders

conversation organization.
CREATE TABLE chat_folders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    user_id INTEGER NOT NULL, 
    name VARCHAR(100) NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

ALTER TABLE conversations ADD COLUMN folder_id INTEGER;

ALTER TABLE conversations ADD FOREIGN KEY(folder_id) REFERENCES chat_folders (id) ON DELETE SET NULL;

CREATE INDEX ix_conversations_user_folder ON conversations (user_id, folder_id);

UPDATE alembic_version SET version_num='0017_chat_folders' WHERE alembic_version.version_num = '0016_agent_runs_awaiting';

COMMIT;

