CREATE TABLE public.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(50) NOT NULL UNIQUE,
    email character varying(255) NOT NULL UNIQUE,
    role character varying(20) DEFAULT 'user'::character varying NOT NULL CHECK (role IN ('admin', 'user')),
    password_hash text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.providers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL UNIQUE,
    provider_type character varying(50) NOT NULL,
    base_url text,
    api_key_env character varying(100),
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.models (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id integer NOT NULL REFERENCES public.providers(id) ON DELETE CASCADE,
    model_name character varying(200) NOT NULL,
    display_name character varying(200) NOT NULL,
    supports_text boolean DEFAULT true NOT NULL,
    supports_streaming boolean DEFAULT true NOT NULL,
    supports_vision boolean DEFAULT false NOT NULL,
    supports_audio boolean DEFAULT false NOT NULL,
    supports_tools boolean DEFAULT false NOT NULL,
    supports_json boolean DEFAULT false NOT NULL,
    context_window integer,
    enabled boolean DEFAULT true NOT NULL,
    UNIQUE (provider_id, model_name)
);

CREATE TABLE public.conversations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    title character varying(100) DEFAULT 'New Chat'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.messages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id integer NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
    role character varying(20) NOT NULL CHECK (role IN ('user', 'assistant')),
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.agents (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL UNIQUE,
    description text DEFAULT '' NOT NULL,
    system_prompt text NOT NULL,
    provider_id integer REFERENCES public.providers(id) ON DELETE SET NULL,
    model_id integer REFERENCES public.models(id) ON DELETE SET NULL,
    temperature numeric(3,2) DEFAULT 0.70 NOT NULL,
    internet_enabled boolean DEFAULT false NOT NULL,
    multimodal_enabled boolean DEFAULT false NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.skills (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL UNIQUE,
    description text DEFAULT '' NOT NULL,
    enabled boolean DEFAULT true NOT NULL
);

CREATE TABLE public.agent_skills (
    agent_id integer NOT NULL REFERENCES public.agents(id) ON DELETE CASCADE,
    skill_id integer NOT NULL REFERENCES public.skills(id) ON DELETE CASCADE,
    PRIMARY KEY (agent_id, skill_id)
);

CREATE TABLE public.mcp_servers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL UNIQUE,
    description text DEFAULT '' NOT NULL,
    connection_type character varying(20) NOT NULL CHECK (connection_type IN ('command', 'url')),
    command text,
    url text,
    enabled boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.agent_mcps (
    agent_id integer NOT NULL REFERENCES public.agents(id) ON DELETE CASCADE,
    mcp_server_id integer NOT NULL REFERENCES public.mcp_servers(id) ON DELETE CASCADE,
    PRIMARY KEY (agent_id, mcp_server_id)
);

CREATE TABLE public.workflows (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL UNIQUE,
    workflow_type character varying(30) NOT NULL CHECK (workflow_type IN ('single_agent', 'sequential', 'supervisor', 'reviewer', 'parallel', 'debate')),
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.workflow_steps (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id integer NOT NULL REFERENCES public.workflows(id) ON DELETE CASCADE,
    agent_id integer REFERENCES public.agents(id) ON DELETE SET NULL,
    step_order integer NOT NULL,
    step_name character varying(100) NOT NULL,
    UNIQUE (workflow_id, step_order)
);

CREATE TABLE public.agent_runs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    conversation_id integer NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
    message_id integer REFERENCES public.messages(id) ON DELETE SET NULL,
    agent_id integer REFERENCES public.agents(id) ON DELETE SET NULL,
    workflow_id integer REFERENCES public.workflows(id) ON DELETE SET NULL,
    parent_run_id integer REFERENCES public.agent_runs(id) ON DELETE CASCADE,
    status character varying(20) NOT NULL CHECK (status IN ('running', 'completed', 'failed', 'awaiting_approval')),
    final_response text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at timestamp with time zone
);

CREATE TABLE public.agent_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_run_id integer NOT NULL REFERENCES public.agent_runs(id) ON DELETE CASCADE,
    event_type character varying(50) NOT NULL,
    title character varying(200) NOT NULL,
    content text DEFAULT '' NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.tool_calls (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_run_id integer NOT NULL REFERENCES public.agent_runs(id) ON DELETE CASCADE,
    skill_name character varying(100) NOT NULL,
    input_summary text DEFAULT '' NOT NULL,
    output_summary text DEFAULT '' NOT NULL,
    status character varying(20) NOT NULL CHECK (status IN ('running', 'completed', 'failed')),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.mcp_calls (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_run_id integer REFERENCES public.agent_runs(id) ON DELETE CASCADE,
    mcp_server_id integer REFERENCES public.mcp_servers(id) ON DELETE SET NULL,
    tool_name character varying(100) NOT NULL,
    input_summary text DEFAULT '' NOT NULL,
    output_summary text DEFAULT '' NOT NULL,
    status character varying(20) NOT NULL CHECK (status IN ('running', 'completed', 'failed')),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.attachments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    message_id integer REFERENCES public.messages(id) ON DELETE CASCADE,
    file_name text NOT NULL,
    mime_type character varying(150) NOT NULL,
    storage_path text NOT NULL,
    size_bytes integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.artifacts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_run_id integer REFERENCES public.agent_runs(id) ON DELETE CASCADE,
    attachment_id integer REFERENCES public.attachments(id) ON DELETE CASCADE,
    artifact_type character varying(50) NOT NULL,
    title character varying(200) NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.sources (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_run_id integer REFERENCES public.agent_runs(id) ON DELETE CASCADE,
    url text NOT NULL,
    title text DEFAULT '' NOT NULL,
    snippet text DEFAULT '' NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.settings (
    key character varying(100) PRIMARY KEY,
    value text NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.connectors (
    slug character varying(50) PRIMARY KEY,
    name character varying(100) NOT NULL,
    description text DEFAULT '' NOT NULL,
    auth_type character varying(20) DEFAULT 'token' NOT NULL,
    token_label character varying(200) DEFAULT '' NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.connector_accounts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    connector_slug character varying(50) NOT NULL REFERENCES public.connectors(slug) ON DELETE CASCADE,
    credentials_encrypted text NOT NULL,
    display_name text DEFAULT '' NOT NULL,
    status character varying(20) DEFAULT 'connected' NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_connector_accounts_user_slug UNIQUE (user_id, connector_slug)
);

INSERT INTO public.connectors (slug, name, description, auth_type, token_label, enabled) VALUES
    ('github', 'GitHub', 'Buscar repos, leer archivos e issues, y crear issues en nombre del usuario.', 'token', 'Personal access token (PAT)', true),
    ('gdrive', 'Google Drive', 'Buscar archivos y leer documentos de Google Drive del usuario (solo lectura).', 'token', 'OAuth access token', true)
ON CONFLICT (slug) DO NOTHING;

CREATE TABLE public.plugin_marketplaces (
    name character varying(100) PRIMARY KEY,
    url text NOT NULL UNIQUE,
    added_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.plugins (
    slug character varying(80) PRIMARY KEY,
    name character varying(150) NOT NULL,
    version character varying(30) DEFAULT '1.0.0' NOT NULL,
    description text DEFAULT '' NOT NULL,
    source character varying(20) DEFAULT 'local' NOT NULL,
    marketplace_name character varying(100) REFERENCES public.plugin_marketplaces(name) ON DELETE SET NULL,
    manifest jsonb NOT NULL,
    installed_refs jsonb NOT NULL,
    installed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.subagent_dispatches (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_run_id integer NOT NULL REFERENCES public.agent_runs(id) ON DELETE CASCADE,
    child_run_id integer NOT NULL UNIQUE REFERENCES public.agent_runs(id) ON DELETE CASCADE,
    agent_name character varying(100) NOT NULL,
    goal text NOT NULL,
    status character varying(20) DEFAULT 'pending' NOT NULL,
    result text DEFAULT '' NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX ix_agent_runs_parent ON public.agent_runs (parent_run_id);
CREATE INDEX ix_subagent_dispatches_parent ON public.subagent_dispatches (parent_run_id);

INSERT INTO public.providers (name, provider_type, base_url, api_key_env, enabled)
VALUES
    ('OpenRouter', 'openrouter', 'https://openrouter.ai/api/v1', 'OPENROUTER_API_KEY', true),
    ('OpenAI', 'openai', 'https://api.openai.com/v1', 'OPENAI_API_KEY', false),
    ('Anthropic', 'anthropic', 'https://api.anthropic.com', 'ANTHROPIC_API_KEY', false),
    ('Gemini', 'gemini', 'https://generativelanguage.googleapis.com', 'GEMINI_API_KEY', false),
    ('Ollama', 'ollama', 'http://127.0.0.1:11434/v1', NULL, false),
    ('llama.cpp', 'llamacpp', 'http://127.0.0.1:8080/v1', NULL, false),
    ('Custom OpenAI-Compatible', 'openai_compatible', NULL, NULL, false)
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.models (
    provider_id,
    model_name,
    display_name,
    supports_text,
    supports_streaming,
    supports_vision,
    supports_audio,
    supports_tools,
    supports_json,
    context_window,
    enabled
)
SELECT p.id, model_name, display_name, supports_text, supports_streaming, supports_vision, supports_audio, supports_tools, supports_json, context_window, enabled
FROM public.providers p
JOIN (
    VALUES
        ('OpenRouter', 'nvidia/nemotron-3-super-120b-a12b:free', 'NVIDIA Nemotron 3 Super 120B', true, true, false, false, false, false, NULL::integer, true),
        ('OpenAI', 'gpt-4.1-mini', 'GPT-4.1 Mini', true, true, true, true, true, true, 1047576, false),
        ('Anthropic', 'claude-3-5-sonnet-latest', 'Claude 3.5 Sonnet', true, true, true, false, true, false, 200000, false),
        ('Gemini', 'gemini-1.5-pro', 'Gemini 1.5 Pro', true, true, true, true, true, true, 2000000, false),
        ('Ollama', 'llama3.1', 'Ollama llama3.1', true, true, false, false, false, true, NULL::integer, false),
        ('llama.cpp', 'local-model', 'llama.cpp local model', true, true, false, false, false, true, NULL::integer, false)
) AS seed(provider_name, model_name, display_name, supports_text, supports_streaming, supports_vision, supports_audio, supports_tools, supports_json, context_window, enabled)
ON p.name = seed.provider_name
ON CONFLICT (provider_id, model_name) DO NOTHING;

INSERT INTO public.skills (name, description, enabled)
VALUES
    ('web_search', 'Search the web and return ranked results.', true),
    ('read_url', 'Read and extract clean content from a URL.', true),
    ('extract_pdf', 'Extract text and metadata from uploaded PDFs.', true),
    ('summarize_document', 'Summarize extracted document content.', true),
    ('analyze_image', 'Analyze an uploaded image with a vision-capable model.', true),
    ('critic_review', 'Review an intermediate answer for quality and accuracy.', true),
    ('final_answer', 'Synthesize a final user-facing answer.', true)
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.agents (name, description, system_prompt, provider_id, model_id, internet_enabled, multimodal_enabled, enabled)
SELECT
    'Default Assistant',
    'Default ObsyGPT text assistant.',
    'You are ObsyGPT, a helpful multi-agent AI assistant. Answer clearly and accurately.',
    p.id,
    m.id,
    false,
    false,
    true
FROM public.providers p
JOIN public.models m ON m.provider_id = p.id
WHERE p.name = 'OpenRouter'
  AND m.model_name = 'nvidia/nemotron-3-super-120b-a12b:free'
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.agents (name, description, system_prompt, provider_id, model_id, internet_enabled, multimodal_enabled, enabled)
SELECT seed.name, seed.description, seed.system_prompt, p.id, m.id, seed.internet_enabled, seed.multimodal_enabled, true
FROM public.providers p
JOIN public.models m ON m.provider_id = p.id
JOIN (
    VALUES
        ('Research Agent', 'Finds useful context and source leads.', 'You are ObsyGPT Research Agent. Identify useful facts, gaps, and source leads. Be concise.', true, false),
        ('Writer Agent', 'Drafts clear final answers.', 'You are ObsyGPT Writer Agent. Turn the available context into a clear answer for the user.', false, false),
        ('Critic Agent', 'Reviews answers for accuracy and omissions.', 'You are ObsyGPT Critic Agent. Improve accuracy, identify missing caveats, and return a corrected final answer.', false, false)
) AS seed(name, description, system_prompt, internet_enabled, multimodal_enabled)
ON p.name = 'OpenRouter'
AND m.model_name = 'nvidia/nemotron-3-super-120b-a12b:free'
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.workflows (name, workflow_type, enabled)
VALUES
    ('Default Single Agent', 'single_agent', true),
    ('Research Then Write', 'sequential', true),
    ('Writer With Critic', 'reviewer', true),
    ('Parallel Draft Review', 'parallel', true),
    ('Debate Then Judge', 'debate', true)
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.workflow_steps (workflow_id, agent_id, step_order, step_name)
SELECT w.id, a.id, seed.step_order, seed.step_name
FROM public.workflows w
JOIN (
    VALUES
        ('Research Then Write', 'Research Agent', 1, 'Research'),
        ('Research Then Write', 'Writer Agent', 2, 'Write'),
        ('Writer With Critic', 'Writer Agent', 1, 'Draft'),
        ('Writer With Critic', 'Critic Agent', 2, 'Review'),
        ('Parallel Draft Review', 'Research Agent', 1, 'Research'),
        ('Parallel Draft Review', 'Writer Agent', 2, 'Draft'),
        ('Parallel Draft Review', 'Critic Agent', 3, 'Critique'),
        ('Debate Then Judge', 'Research Agent', 1, 'Position A'),
        ('Debate Then Judge', 'Writer Agent', 2, 'Position B'),
        ('Debate Then Judge', 'Critic Agent', 3, 'Judge')
) AS seed(workflow_name, agent_name, step_order, step_name)
ON w.name = seed.workflow_name
JOIN public.agents a ON a.name = seed.agent_name
ON CONFLICT (workflow_id, step_order) DO NOTHING;

INSERT INTO public.agent_skills (agent_id, skill_id)
SELECT a.id, s.id
FROM public.agents a
JOIN (
    VALUES
        ('Research Agent', 'read_url'),
        ('Research Agent', 'web_search'),
        ('Critic Agent', 'critic_review'),
        ('Writer Agent', 'final_answer'),
        ('Default Assistant', 'final_answer')
) AS seed(agent_name, skill_name)
ON a.name = seed.agent_name
JOIN public.skills s ON s.name = seed.skill_name
ON CONFLICT (agent_id, skill_id) DO NOTHING;
